name: format-lint

on: push

jobs:
  format-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: coding-practice
        python-version: 3.8
        auto-activate-base: false
    - name: Setup
      shell: bash -l {0}
      run: make setup-dev
    - name: Format with black and isort
      shell: bash -l {0}
      run: make format
    - name: Lint with flake8, mypy and pylint
      shell: bash -l {0}
      run: make lint